### ISSUE TITLE
Decimation effects when gridsize is not an integer

### ISSUE THREAD

**Issue by szi** [sdmiller/cpu_tsdf#11]
Hi,

I seem to be getting incorrect looking meshes (large lines throughout the entire mesh, as if some voxel indexing is off by one for certain rows/columns in the grid) when I pick a gridsize that's not an integer, even though I think it should accept float values. My resolution is 1024.

In your example you use 10.0 as grid size. Could you try changing it to e.g. 10.1, 10.5 and see if you get similar artifacts in your reconstructions? If so, it might be a problem with the voxel indexing or some implicit float/integer conversion within the code?  

I came across this because I auto-generates the grid-sizes for my particular problem size. For now I will just ceil(...) them...

Thanks!

**Comment by sdmiller** [comment]
Hi @szi ,

Thanks for the heads up, and sorry about the delay. I was just getting to this today, and since I've switched to OSX, I've realized I (embarrassingly) no longer have a dataset to test on! See: https://github.com/sdmiller/cpu_tsdf/issues/14

If you could provide me with an example dataset where you see this problem, I'd be happy to debug it. Feel free to drop me a line at sdmiller@stanford.edu
