### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by billyzepho** [sdmiller/cpu_tsdf#18]
When i provide the clouds with their poses , lets say clouds1-100
the algorithm runs first for cloud 10 then cloud 1 2-3...9 etc , i think it might be a problem with
the sorting function

**Comment by sdmiller** [comment]
Hi Billy,

Yes, unfortunately I'm fairly agnostic to input and am only using std::sort
to sort these files -- this is a biprodoct of me not constraining the file
prefix, so it's hard to enforce any pattern like xyz10 > xyz2.

If you're interested in modifying the sorting function, feel free -- that
executable is mainly for testing. Otherwise I'd suggest a simple bash
script to prepend 0's (replacing cloud?.png with cloud0?.png, etc)

**Comment by billyzepho** [comment]
Ok now after some googling i see its more complicated than i thought.
I just save the files in cloud???.pcd format as you suggested and it worked.
This is the code that solved the issue for me: 
http://stackoverflow.com/questions/4930492/integer-value-problem
Thank you for your help
