### ISSUE TITLE
tsdf->renderView only shows sparse point cloud?

### ISSUE THREAD

**Issue by xudi1227** [sdmiller/cpu_tsdf#22]
Hi @sdmiller ,

I know it's an old project but I really appreciate your help.

The whole pipeline works fine for me, except the `tsdf->renderView` part. My point cloud looks like this:
![2](https://cloud.githubusercontent.com/assets/6670126/22646580/0d5fbd26-eca8-11e6-9cdb-9f6250d972ca.png)
But when I run the `renderView` and show the generated PCD, it lost a lot points:
![1](https://cloud.githubusercontent.com/assets/6670126/22646578/0a599fca-eca8-11e6-8a4a-f47e5cfbf8cb.png)

I tried smaller size voxels and other parameters, but it didn't help. I guess the problem is the the ray casting part of  `renderView` . If I replace `step = std::max (voxel->getMinSize () / 4., fabs (d)*max_dist_neg_)` with a smaller value, I can get more points, but not all of them.

Are there  any parameters I should tune? Or could you explain a bit about what's going on inside  `tsdf->renderView`?

Many thanks,
Johnny

**Comment by sdmiller** [comment]
Could you let me know how many point clouds you're aggregating? The TSDF does have a minimum weight (I believe the parameter is min_weight, would need to dig into the code) so if overlap is too small, you may see spotty results like this.

Could you also show the mesh output? This could help determine if it's the TSDF itself that is failing, or simply the rendering code.

**Comment by xudi1227** [comment]
Thanks for replying. 
Currently I'm only using 1 point cloud. I read in 1 cloud, transfer it to tsdf, and then run the renderview. That means there's only 1 set of tsdf values.
The matching cube function is able to produce dense point cloud with enough resolution. It works fine. I can post the figure when I'm back to the office.
My question is about the renderview function. I can only get a sparse point cloud using it. The ray casting part is a bit difficult to understand. I cannot produce a dense cloud by tuning the parameters.

Thanks,
Johnny

**Comment by xudi1227** [comment]
Hi @sdmiller ,

Below is the mesh output. I chang the cell-size to 0.0001 and it looks dense enough. 
![3](https://cloud.githubusercontent.com/assets/6670126/22673580/0f223832-ed16-11e6-97ba-9d0bdfc556d5.png)

Thanks,
Johnny

**Comment by sdmiller** [comment]
Hi Johnny,

So that's the problem; the TSDF is meant to aggregate many viewpoints, not simply one. The smaller your cell size is, the more likelihood there is that some cells won't have any observations yet: I wrote this in a way where each point reading would only project to one voxel, not many.

My first suggestion would be to not necessarily use this approach for a single cloud: I don't think you gain anything from trying to create a mesh from that: the benefit of the SDF is denoising, and with only one reading you don't get any time to do that. Other meshing algorithms, like some simple Delauney triangulation, will probably do better.

If you'd like this to work with very few readings, there are two things you can do. One is increase the voxel size (probably 1cm - 3cm would do). Another is lower the minimum marching cubes weight to 0 via "MarchingCubesTSDFOctree::setMinWeight(0)"

**Comment by sdmiller** [comment]
In other words, this might simply be the way I wrote it -- I don't think I had in mind a single snapshot. Much of the aggregating assumes there will be many points (or at least a few) before it commits to a render.

**Comment by sdmiller** [comment]
Yup, revisiting the code a bit, I think this has to do with my attempts to save space by partitioning voxels. I think at the moment we are rendering, most voxels are still very big -- they haven't been split down to the leaf level yet. This means the render function (which wasn't particularly well optimized, or written for that matter) is probably seeing lots of "empty" voxels when, in reality, they're simply supervoxels that haven't been given enough time to split.

**Comment by xudi1227** [comment]
Hi @sdmiller ,
Thanks for the explanations. It helps me understand the pipeline better.
Actually for some reasons I'm purposely testing single cloud->TSDF. I did a little change inside `getFrustumCulledVoxels` so now I can save the all the voxels centers after splitting as a point cloud:
![snapshot01](https://cloud.githubusercontent.com/assets/6670126/22733433/b87b622a-ee2c-11e6-8d5d-a06b2577adfd.png)
The object looks dense enough while the surroundings didn't split. This means the voxel splitting works fine. So I guess my question is still on the `renderView` part. The way it generates the point cloud is using ray casting to find the 0-crossing voxels. The ray casting is from a "**single**" view, and each ray is supposed to hit only one 0-crossing pairs and save them as point cloud. This is where I got a bit lost, why is that single view? Do you still remember the logic behind this? 
If I want to see the ray casting results of TSDF from the view window, shall I do ray casting  based on the current view of the window? What I mean is to interactively see the result from a different view whenever I rotate or move the TSDF in the window.

Thanks,
Johnny

**Comment by sdmiller** [comment]
Aha, yes, I understand now. Sorry, been a long couple of days :)

So the point of the rendering logic is to fill in a gap in the Levoy et al pipeline that Kinect Fusion uses. They iteratively build a TSDF, then use ICP to align to the TSDF, and repeat. For that second step, they compare the current point cloud they are seeing from the sensor (X,Y,Z pixel map), with a synthetic one generated from the TSDF (also an X,Y,Z pixel map). That's why this is ray casting: it's saying "show me the point cloud I would be seeing, if I were at this exact pose looking at the map I already built." By initializing that to pose(t-1), then aligning the observed cloud with the synthetic cloud, you can infer pose(t). (Note that these are organized point clouds, so they can be indexed by cloud->at(x,y) to reconstruct a dense depth image.)

In general, the two nicest ways to look at a TSDF are either to run marching cubes to get a mesh (loses some of the beauty of course) or to plan a synthetic fly-around of the scene, and render each view on the fly. The most beautiful way to render it that I provided was this method:
```
    /** \brief Get a raytraced surface, for visualizing */
    pcl::PointCloud<pcl::Intensity>::Ptr
    getIntensityCloud (const Eigen::Affine3d &trans 
                        = Eigen::Affine3d::Identity ()) const;
```
which is an imitation of KinectFusion's visualizer. I believe PCL provides a direct way to view an intensity cloud, or you can grab the intensity values directly to build your own grayscale view of the TSDF. This will look pretty much exactly like what you've seen in KinFu/Kintinuous/etc demos.

**Comment by xudi1227** [comment]
Oh I see. Thanks a lot.

For the 2nd way you mentioned ( render each TSDF view on the fly), I found the code was not finished in line 544 of `tsdf_volume_octree.cpp`  :
`pcl::PointCloud<pcl::Intensity>::Ptr
cpu_tsdf::TSDFVolumeOctree::getIntensityCloud (const Eigen::Affine3d &trans) const
{
 // TODO
  return (pcl::PointCloud<pcl::Intensity>::Ptr ());
}`

Have you finished this part by any chance? Or could you give some hint where to start?

**Comment by sdmiller** [comment]
Wow, this is embarrassing. I must have only implemented it in a side project, not the original repository.

If you search for a similar function in the pcl::KinFuTracker class, I think you will find the logic there. It shouldn't be drastically different from that of the normal raytracing step; it just needs to also calculate normals.
